language: c
script: asdf plugin-test deno https://github.com/johnlayton/valdastreet.git 'deno version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx